### ISSUE TITLE
Validating issuer with multi-tenant should not just turn validate issuer off.

### ISSUE THREAD

**Issue by brentschmaltz** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#36] opened 2019-01-31 16:28 UTC
The suggested code is: 

> TokenValidationParameters = new System.IdentityModel.Tokens.TokenValidationParameters
{
   ValidateIssuer = false,
}

An alternative is to set the delegate: TokenValidationParameters.IssuerValidator

Control will be passed to this delegate that has a signature: 
(string issuer, SecurityToken securityToken, TokenValidationParameters validationParameters)

The application can then make a dynamic decision determining if the issuer is valid.

**Comment by kalyankrishna1** [comment] 2019-02-05 01:22
Brent, we've provided an example delegate implementation at Utils\AadIssuerValidator.cs

**Comment by brentschmaltz** [comment] 2019-02-08 21:21
Using the delegate seems correct.
How do the issuers get populated into TokenValidationParameters?

**Comment by kalyankrishna1** [comment] 2019-02-12 06:54
The method [BuildTokenValidationParameters](https://github.com/Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect/blob/b2e0ecd61872b8d8fbc4e9c1c590e5e7e62d07c6/TodoListWebApp/App_Start/Startup.Auth.cs#L118) does it.
The sample's first step if for admins to first sign-up and admin consent the app in a tenant. Then the users can proceed to sign in.
In this method, the "signed-up" tenants are saved in the DB and this method provides them as a list of valid tenants whose users are allowed to sign-in .

**Comment by jmprieur** [comment] 2019-04-04 08:32
Closing this issue as the problem is solved

**Closed** 2019-04-04 08:32 UTC
