### ISSUE TITLE
Multi-tenant Not Working When Running in Azure Government Tenant

### ISSUE THREAD

**Issue by dougahall** [Azure-Samples/active-directory-dotnet-webapp-multitenant-openidconnect#30] opened 2017-12-21 18:37 UTC
I was able to run this sample successfully from a commercial AD tenant and log in with users from multiple tenants. However, when I register the app in a government tenant and try to register as a user from a different AD tenant, I'm getting the following error:

`Application with identifier '9240c326-325a-48e2-8382-0efde95ee41e' was not found in the directory sasdomain1.onmicrosoft.com`

- I have followed all the steps in the instructions.
- I've taken the specific steps outlined for making it work in Azure Government.
- Once completed, I can log in with a user account in the government tenant that the app is registered but when attempting to log in with a user from a different AD tenant I get the above error.

The user's tenant allows users to consent to apps accessing company data on their behalf.
I have double-checked the app registration and the "availableToOtherTenants" flag is true.

Here is the error including the correlation ID from my last attempt:

```
Correlation ID: f7b94d33-0aa9-4ea4-b2b2-13184d9d0f37
--
Timestamp: 2017-12-21 14:58:19Z
AADSTS70001: Application with identifier '9240c326-325a-48e2-8382-0efde95ee41e' was not found in the directory sasdomain1.onmicrosoft.com

```
Any help would be greatly appreciated.

**Comment by Josh-Stadfield** [comment] 2018-02-08 00:01
I am having a very similar issue

` Request Id: ee1c22f4-ac4e-4ecd-8cf7-c9aba7490100
Correlation Id: 339553ac-0d07-48f3-a33e-2b559b91ca40
Timestamp: 2018-02-08T00:00:32Z
Message: AADSTS70001: Application with identifier 'd3f22e24-b87b-4ba2-8c88-4ae572c31982' was not found in the directory alabamaui.com `

**Comment by Josh-Stadfield** [comment] 2018-02-08 00:52
Oh, and I did read the readme and applied the changes required for azure government cloud. Including adding the visual studio extension and connecting with my account.

**Comment by anthonyrubalcaba** [comment] 2018-09-11 15:50
I am having the same issue. Followed all the steps and got multi-tenant application working against users from multiple public AADs. When following the same configuration steps in Azure government I am getting the error that the application with identifier was not found in the users' home directory. I have read from https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-plan-identity this: 

If you choose Azure AD Public identities for your Azure Government application, you must register the application in your Azure AD Public tenant. Otherwise, if you perform the app registration in the directory the subscription trusts (Azure Government) the intended set of users cannot authenticate.

but I am unable to find instructions for how to register an app in a public cloud if the app lives in a gov cloud.

**Comment by JoshFieldstad** [comment] 2018-09-11 17:48
Just following up because I got a ping from your comment, the issue is that multitenant apps are not supported in Azure Gov US yet.  When I talked to them in May there was no ETA.

**Comment by negoe** [comment] 2018-09-13 18:44
About registering an app in public cloud you can go to portal.azure.com. You would need to register the app in both Public and Azure Government (portal.azure.us) separately. 
These would be two separate instances of the App registration and managed independently.

About having a multi-tenant app in Azure Government, a multi-tenant application in Arlington will not be accessible from public cloud.

**Comment by kalyankrishna1** [comment] 2019-02-12 06:45
Closing as OP has not responded

**Closed by kalyankrishna1** 2019-02-12 06:45 UTC
